name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Configure
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false

      - name: Checkout target
        run: | 
          git checkout gh-pages
          git merge master
          git pull origin gh-pages

      - name: Build
        run: make build

      - name: Commit
        run: |
          git status
          git add ./docs
          git commit -m "automated build" && git push || true
